### ISSUE TITLE
[hackathon] Ciphersuite default values

### ISSUE THREAD

**Issue by hisanak** [ietf-teep/teep-protocol#182]
Related to [#176 Pull Request](https://github.com/ietf-teep/teep-protocol/pull/176) recently merged, I think it is beneficial for implementers to clarify the default values in QueryResponse.options.selected-cipher-suites too.
How about to add a bold sentence like below?

> The selected-cipher-suite parameter indicates the selected ciphersuite. **If this parameter is not present, it is to be treated as if it contained all ciphersuites listed in the QueryRequest.** Details about the ciphersuite encoding can be found in {​​​{​​​​​​​​​​ciphersuite}​​​​​​​​​​​​​​​​​}​​​​​​​​​​​​​​​​​.

NOTE: Related parts of the current draft

| Message type  | Option name             | Description |
|---------------|-------------------------|-------------|
| QueryRequest  | [supported-cipher-suites](https://github.com/ietf-teep/teep-protocol/blob/0188f6b74661594bb329a54a5392963200d4eaf6/draft-ietf-teep-protocol.md?plain=1#L363-L366) | The supported-cipher-suites parameter lists the ciphersuites supported by the TAM. If this parameter is not present, it is to be treated the same as if it contained all ciphersuites defined in this document that are listed as "MUST". Details about the ciphersuite encoding can be found in {{ciphersuite}}. |
| QueryResponse | [selected-cipher-suite](https://github.com/ietf-teep/teep-protocol/blob/0188f6b74661594bb329a54a5392963200d4eaf6/draft-ietf-teep-protocol.md?plain=1#L447-L449)   | The selected-cipher-suite parameter indicates the selected ciphersuite. Details about the ciphersuite encoding can be found in {{ciphersuite}}. |
| Error         | [supported-cipher-suites](https://github.com/ietf-teep/teep-protocol/blob/0188f6b74661594bb329a54a5392963200d4eaf6/draft-ietf-teep-protocol.md?plain=1#L941-L944) | The supported-cipher-suites parameter lists the ciphersuite(s) supported by the TEEP Agent. Details about the ciphersuite encoding can be found in {{ciphersuite}}. This otherwise optional parameter MUST be returned if err-code is ERR_UNSUPPORTED_CIPHER_SUITES. |

**Comment by kentakayama** [comment]
Ah, I created this Issue with my private account...
But its me 😄

**Comment by mcd500** [comment]
@dthaler Do you also mind commenting on this, the PR is made it at https://github.com/ietf-teep/teep-protocol/pull/204.

This was from last IETF 113 hackathon, so I would like to move on.

**Comment by dthaler** [comment]
The proposed change does not make sense to me.   supported-cipher-suites is a list:
```
? supported-cipher-suites => [ + suite ],
```
whereas selected-cipher-suite is a singleton:
```
    ? selected-cipher-suite => suite,
```

It is not possible for a singleton to "contain all ciphersuites listed in the QueryRequest".

**Comment by dthaler** [comment]
I think the real question is: what does it mean if the selected-cipher-suite is absent?   Personally, I would be ok wither either of the following 2 resolutions:

a. Make selected-cipher-suite mandatory instead of optional, or 
b. Say absence indicates a particular set of mandatory algorithms. 

There's two mandatory signing algorithms (cose-alg-es256 and cose-alg-eddsa) though so don't know what to do about picking between them, so would probably prefer (a).   It looks like right now the syntax allows a suite to have multiple signing algorithms.  What does it mean to select two signing algorithms for communication?   Why isn't it just one?

**Comment by kentakayama** [comment]
@dthaler 
I prefer to remain the `selected-cipher-suite` optional, but slightly differ from (b). How about this one?

c. The absence of `selected-cipher-suite` indicates "no preference on ciphersuite, any ciphersuite in `supported-cipher-suite` is acceptable" so the TAM SHOULD select it from `supported-cipher-suites`.

With option (c), the TEEP Agent MAY decide not to select the ciphersuite in the TEEP Protocol. I think it would be natural to keep using the ciphersuite used in the TAM's first QueryRequest message, but I don't want to make it clear in the document because some TAMs and TEEP Agents may pre-define or negotiate the ciphersuite out of TEEP Protocol.
This is consistent with the current draft, because the TEEP Agent MAY explicitly select the preferable ciphersuite in the QueryResponse message, and in case there is no supported ciphersuite, the TEEP Agent can reply with Error message to tell the TEEP Agent's `supported-cipher-suites`.

**Comment by dthaler** [comment]
Fixed in draft -09
