### ISSUE TITLE
explain randomness of tokens better

### ISSUE THREAD

**Issue by mcr** [ietf-teep/teep-protocol#239]
section 4.2:
} The TAM SHOULD set an expiration time for each token and MUST ignore any
} messages with expired tokens. The TAM MUST expire the token value after
} receiving the first response containing the token value and ignore any
} subsequent messages that have the same token value.

I guess this is a defense against replays.
I guess this document hasn't told me if it's over HTTP or carrier pigeon yet :-)
How does the TAM know that the *first* isn't invalid?
I guess it has already validated the message, so it must be okay.
This isn't a replay window here.  Some motivation for what attack we are
resisting here would be good.

**Comment by dthaler** [comment]
Section 4.2 says, just before the text cited in the issue above:

> The value in the token parameter is used to match responses to requests. This is particularly useful when a TAM issues multiple concurrent requests to a TEEP Agent.

This, it allows the TAM to look up any implementation-specific state it saved about that request. 

and
> The TAM SHOULD set an expiration time for each token and MUST ignore any messages with expired tokens. 

I think this phrase is to make sure TAM state is cleaned up if a TEEP Agent dies in the middle of an exchange.

I think the mechanism is also for this case:
* someone is choosing to not use attestation per se for some reason beyond me
* TAM sends a QueryRequest
* Time passes
* TAM policy changes, e.g. supported cipher suites or supported freshness mechanisms
* Another QueryRequest is sent but this time with different fields due to the policy change
* The reply from the first QueryRequest finally arrives.
* The TAM now wants to know if the QueryRequest was in response to the one with the old policy or the one with the new policy

**Comment by dthaler** [comment]
Fixed in draft-11
