### ISSUE TITLE
A Compromised Agent wants to theft Attestation Results from a healthy Agent.

### ISSUE THREAD

**Issue by ko-isobe** [ietf-teep/teep-protocol#310]
Under using sign-only TEEP messages, an attacker can obtain Attestation Results (AR) from QueryResponse.
The attacker makes TAM trust by malformed QueryResponse with genuine AR.
To be more specific, if an attacker has device A' whose Agent is compromised, the attacker can pretend non-compromised device A by sending QueryResponse with A's AR.  
`challenge` in AR is used to guarantee the freshness of AR. But in the current drafts, TAM doesn't need to expire the challenge when receiving AR just once.

To tackle this situation, we can use encryption to make TEEP messages confidential.
For example, using COSE_Enc in TEEP messages and using TLS are countermeasures.

In the current draft section 8, encryption is used to keep manifests confidential.

Should we imagine this compromised Agent situation? And add documentation as a new use case for using encryption?

**Comment by mingpeiwk** [comment]
This will be a significant change to the protocol spec. I would like to understand the concern better before we propose any necessary change.

An attack could have a compromised device A'. Devices are typically expect to have unique device keys for signing an AR. A' won't have A's signing key; but assume A' has a key and a device certificate that is issued by the legitimate manufacturer and therefore its device CA. Such a device A' will be trusted by a TAM by supplying data with its key. Device compromise and device CA compromise are all part of security concerns. The question is whether an encryption will mitigate such a risk, and how A' can act as A.

In the given example, A' doesn't have A's key. How does it impersonate a device A? The assumption is that an attack somehow gets device A's AR from device A before TEEP Broker sends out, which typically uses a secure channel to a TAM. So this assumes device A's compromised, not only device A'. @ko-isobe could you elaborate? We can chat in email out of band from here.

There is a separate question about end-to-end encryption from a TEEP Agent to TAM. The concern was on the confidentiality of other data such as installed Trusted Component ID list (? tc-list => [ + system-property-claims ]) in an AR, assuming that some scenario doesn't want to reveal to others what are running in user's devices. The support of entire TEEP message encryption while keeping some metadata (token, selected-teep-cipher-suite etc.) is complex. The main device privacy information comes from the attestation-payload, which already has a recommendation encryption support method.

The doc has mentioned the following:

"Although this specification only specifies the use of signing and relies on payload encryption to protect sensitive information, future extensions might specify support for encryption and/or MAC operations if needed."

I incline to defer this not as a high concern by continuing to leave it to a future extension, and would like to hear more feedback.

**Comment by hannestschofenig** [comment]
Akira raises an interesting question, namely whether an attacker can steal the Attestation Results (AR) on one device and use it for another. (I am assuming that the Attestation Result contains information about the intended recipient, i.e. the "Other Relying Party". This allows an attacker to only use the Attestation Result by a different TEEP Agent rather than even with a different relying party.)

Here is the relevant figure from the draft.

![image](https://user-images.githubusercontent.com/1016643/224543267-78f040a9-9424-48cb-8e15-07471deb6445.png)

The question for me is how is the attestation result bound to the involved parties. 

For example, how does the "Other Relying Party" know that the Attestation Result sent from the TEEP Agent is fresh and that the TEEP Agent is indeed the party it wants to talk to. An attacker could be located somewhere between the TEEP Broker and the TEEP Agent and capture the Attestation Result.

FWIW it would not help to encrypt the Attestation Result by the Verifier for decryption by the "Other Relying Party" alone since there is still the link missing to the specific TEEP Agent instance. Hence, the Verifier has to include some information about the TEEP Agent, which can be verified by the "Other Relying Party". 

IMHO this is not a TEEP issue alone but a RATS issue in general. One solution is to move away from bearer tokens, which is what the attestation result is, to a proof-of-possession token. FWIW this is something that has been solved in the OAuth working group in two ways, namely via [RFC 8705 ](https://datatracker.ietf.org/doc/rfc8705/) and also via [draft-ietf-oauth-dpop-14](https://datatracker.ietf.org/doc/draft-ietf-oauth-dpop/).

**Comment by dthaler** [comment]
> Under using sign-only TEEP messages, an attacker can obtain Attestation Results (AR) from QueryResponse.

A QueryResponse can have an attestation payload that could be either Evidence or Attestation Results, and would be Evidence in the picture (Figure 1) that Hannes cites, where TEEP uses a Background Check model.  So I assume this is not about that case, but instead about a case where Attestation Results are included instead, using a Passport model.   The Passport model is designed to allow the same Attestation Results to be potentially presented to many Relying Parties, much as human passports and drivers licenses are used.   As such, encrypting the TEEP protocol is not the right solution for that problem, since any other Relying Party that the same Attestation Results are presented to, could attempt the same thing even if TEEP messages were encrypted.

So the statement so far should simply be "an attacker can obtain Attestation Results (AR) from the victim", which is true.  This by itself is typically not a security flaw, unless the Verifier chooses to put sensitive information in the AR, and if it does then it's up to the Verifier to secure it in my opinion.

> The attacker makes TAM trust by malformed QueryResponse with genuine AR. To be more specific, if an attacker has device A' whose Agent is compromised, the attacker can pretend non-compromised device A by sending QueryResponse with A's AR. `challenge` in AR is used to guarantee the freshness of AR. But in the current drafts, TAM doesn't need to expire the challenge when receiving AR just once.

Here the security problem is if a TAM (being a Relying Party) believes the copied AR actually goes with the secure communication channel from the Attester to the Relying Party, and as Ming observed this is not specific to TEEP per se.
What is needed to prevent that isn't encryption, it's to cryptographically bind the AR to the key used to sign TEEP messages.
So for example if the AR contains, in a claim, a hash/fingerprint of a public key of the attester, and the QueryResponse is signed with the corresponding private key, then the attack is prevented because the attacker doesn't have the private key to sign with, and so validating the AR will fail.

Hence discussion of encryption is a red herring, what's needed is a cryptographic check that the AR is the TEEP Agent's AR, such as described above.

**Comment by mingpeiwk** [comment]
Concur on Dave's proposal. Thanks.

**Comment by ko-isobe** [comment]
Thanks for consideration, Ming.
I'm assuming the device A and A' have the same Agent key.
This case is when a manufacturer deploys a single Agent key in many same model devices. 
In TEEP architecture draft, while Attestation Results are using for identifying devices, but TEEP Agent keys are not always that purpose. From my understanding, each TEE system has a unique key, but TEE instances are not necessary using unique keys.
The above manufacturer may assign the identifier role of devices the unique Attestation keys. 
In this case, compromised A' and non compromised A are co-exist.

But @kentakayama  suggested to me that if there is a compromised Agent A', all device A which have same Agent key, are not trustworthy.
TAM should treat all device A as non trustworthy Agent because TAM can't distinguish the proper or malformed message signed by the its Agent key .
So I think we don't have to tackle in this situation such as compromised and non-compromised are co-exist in the specification.


Before submitting this issue, I tried to find the "Agent key attestation" method in the current drafts.
Of course, you can use Attestation Results to ensure the secure keeping of Agent private key by your custom claims. But there are no mentions in the former TEEP specification, thus I can't hire this way as a common approach. 

Now Dave suggests an extension of EAT profile which is adding `cnf` to convey the Agent key information. That's a good change in that TAM can commonly verify the status of a TEEP Agent by its Agent key status.

**Comment by mcd500** [comment]
Based on my experience, typically the device of the product has two type of keys.
One key is the same access the same model number, another is unique for each device.
Using for the latter would be ok in this case.

**Comment by dthaler** [comment]
> I'm assuming the device A and A' have the same Agent key. This case is when a manufacturer deploys a single Agent key in many same model devices. 

That should not be permitted.  All keys mentioned in the TEEP architecture are intended to be unique per instance.  A private key is never shared among multiple instances.

**Comment by mingpeiwk** [comment]
> I'm assuming the device A and A' have the same Agent key.
There is the case of the same public key while the private keys are always required to be unique per device in TEEP. Assume "Agent key" means the public key in the claim. The merit of impersonalization of the same group public key, as claimed in "cnf", still applies; the devices are considered in the same status in this case. In all cases, "cnf" addition solved the original concern.

**Comment by kentakayama** [comment]
@dthaler 
> > I'm assuming the device A and A' have the same Agent key. This case is when a manufacturer deploys a single Agent key in many same model devices.
> 
> That should not be permitted. All keys mentioned in the TEEP architecture are intended to be unique per instance. A private key is never shared among multiple instances.

I agree, unique key per instance is ideal, but It may limit Agent implementations.
For example, Intel SGX has sealing function that allows Agent to store some secrets into memory/disk with encryption, and it can be decrypted inside Enclaves having same MRENCLAVE, MRSIGNER, etc. (configured with `SGX_KEYPOLICY_*`).
It helps Agents to restore the private key after machine reboot, but results in the situation where multiple Agents have the same private key (or secret key).

The implementation is like below:
1. Broker creates an Enclave running the Agent
2. Agent requests Broker to search the sealed private key file,
2.1. if exists unseals it
2.2. if not, creates new key pair and seals it, and requests the TAM to execute remote/local attestation
3. Now Agent has private key trusted by the TAM, so that they can exchange TEEP messages securely

But the Broker can create another Enclave running an Agent (Agent') from the same executable binary.
Agent' unseals the private key (2.1.), and now multiple Agents have the same private key.

Should we prohibit Agents to seal the private key used on signing TEEP messages?
This problem happens not only signed TEEP messages, but also MACed and encrypted ones.

**Comment by mcd500** [comment]
> But the Broker can create another Enclave running an Agent (Agent') from the same executable binary. 
>  Agent' unseals the private key (2.1.), and now multiple Agents have the same private key. 

 

The Broker mentioned above is the situation when the Broker is compromised on the SGX salutation, however, I highly believe it is purely a matter in the above implementation and not the TEEP Protocol design issue. 

It must have a reasonable way to implement the TEEP Agent on the SGX. 

We may discuss this at the IETF 116 hackathon.

**Comment by kentakayama** [comment]
https://github.com/ietf-teep/teep-protocol/issues/310#issuecomment-1467297393

In the discussion in IETF116 hackathon with @dthaler and @mcd500 , we concluded that multiple not-compromised Agents running on the same SGX chip does not matter.
Even the Agent seals the private/secret keys into a file and another Agent instance read it, there is no key leakage: only Agents that have the same binary can unseal it.
