### ISSUE TITLE
Mandatory SUIT_Envelope attributes in TEEP

### ISSUE THREAD

**Issue by naga-lep** [ietf-teep/teep-protocol#79]
In SUIT manifest I-D, there are 2 attributes mandatory of SUIT_Envelope.
- suit-authentication-wrapper
- suit-manifest

And TEEP has own "security wrapper".
So, it will be signed twice by TEEP's "security wrapper" and SUIT's "suit-authentication-wrapper".

Would like to clarify who is going to be signer of each of them. 
The TEEP's "security wrapper" is signed by TAM?
The SUIT's "suit-authentication-wrapper" is signed by TC singer?
Or we could omit either and use only one wrapper for singing?

**Comment by dthaler** [comment]
Correct that TEEP messages are signed by TAM, and SUIT manifests are signed by the TC signer.

As discussed in https://tools.ietf.org/html/draft-ietf-teep-architecture-13#section-5 (especially figure 4):
1) the TAM is what authorizes apps to be installed/updated/deleted on a given TEE and the signature is checked by the TEEP Agent at protocol message processing time.  The TEEP security wrapper is also used on messages like QueryRequest so that Agents only send potentially sensitive data such as evidence to trusted TAMs.
2) the TC signer is what authorizes apps to actually run, so the signature could be checked at install time or load (run) time or both, and this checking is done by the TEE independent of whether TEEP is used or something else.

**Comment by dthaler** [comment]
Fixed in draft -05
